### ISSUE TITLE
cuids will not be monotonically increasing in 40 years...

### ISSUE THREAD

**Issue by nknapp** [ericelliott/cuid#108]
...because

`(Date.now()+1000*60*60*24*365*40).toString(36) === 'zlm3vrqf'`

and

`(Date.now()+1000*60*60*24*365*41).toString(36) === '1003nlm00'`

so there will be a 2058 problem...

This is merely a fun-fact, but I found it interesting to share...

**Comment by ericelliott** [comment]
Interesting! I knew there was a limit, but didn't bother to figure out what it was, because I suspected it would be a long time before we need to address it.

Possible fix? Change the prefix from `c` to `c~` just prior to the roll-over? =)

**Comment by MarkHerhold** [comment]
Or `c` -> `d` 😆

**Comment by ericelliott** [comment]
Yes
