### ISSUE TITLE
Simple and effective CUID regex?

### ISSUE THREAD

**Issue by brikou** [ericelliott/cuid#118]
I've already check isCuid method, but this fn only check that it is a string starting by "c"

Do you know a simple and effective way to check that given string look like a real CUID?

Thanks for your great lib :+1:

**Comment by MarkHerhold** [comment]
See https://github.com/ericelliott/cuid/issues/88

**Comment by brikou** [comment]
thanks @MarkHerhold

**Comment by supermacro** [comment]
> Basically there are no other guarantees.

Erm. No. There is definitely a defined set of values that a cuid is comprised of. I'm re-posting my screenshot here from #88 to help others in case they're looking for something a bit more definitive. 

![Screen Shot 2021-03-24 at 7 50 53 PM](https://user-images.githubusercontent.com/10621548/112398522-ca510a80-8cda-11eb-93fe-49c44c80d122.png)

**Comment by ericelliott** [comment]
I do not recommend using a regex to validate cuids.
