### ISSUE TITLE
What is the reason for "c" prefix?

### ISSUE THREAD

**Issue by gajus** [ericelliott/cuid#173]
Beyond "identifies this as a cuid", what is the reason for the "c" prefix?

The documentation states "allows you to use it in html entity ids" – it is not clear what is meant by this, since the next character is always (?) "h" anyway.

**Comment by pendenaor** [comment]
not always `h`, because it's the timestamp part in base 36, which may, one day, become `i`.

**Comment by gajus** [comment]
Understood. Thank you.
