### ISSUE TITLE
Modularize

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/cuid#25]
Please complete [#24](https://github.com/ericelliott/cuid/issues/24) first.

## Stop using the hacky concat build.

* [x] Use ES6 modules
* [x] Drop applitude support (it's obsolete)
* [x] Use separate client/server build entry points and share common features between them.

```
.
└── cuid
    ├── build
    │   ├── client
    │   └── server
    ├── source
    │   ├── client
    │   └── server
    └── test
        ├── client
        └── server
```

## Ignore build directory in diffs

You can [ignore build files in diffs](https://github.com/gitlabhq/gitlabhq/issues/6916#issuecomment-62520577).

Create a .gitattributes file in the repo root:

```
build    -diff
```

**Comment by therealklanni** [comment]
What approach did you have in mind for the build? Browserify for client?

**Comment by therealklanni** [comment]
OK, I see that the boilerplate mentioned in #24 uses webpack, so I'll assume that.

**Comment by ericelliott** [comment]
Yep. Webpack! =)

**Comment by therealklanni** [comment]
Works pretty well with ES6. I'm not sure the minification is working, though. I'll have to look at the webpack docs on that.

**Comment by therealklanni** [comment]
Seems testling is experiencing [technical difficulties](https://github.com/substack/testling/issues/111). What do you want to use for client tests?

**Comment by therealklanni** [comment]
@ericelliott you originally had `slug` as a method on `cuid`, would you be OK with changing that so they can be imported independently (recommended)?

```js
import { cuid, slug } from 'cuid.js'
```

**Comment by ericelliott** [comment]
> Seems testling is experiencing technical difficulties. What do you want to use for client tests?

[blue-tape (see boilerplate)](https://github.com/ericelliott/prod-module-boilerplate/blob/master/test/index.js), run client tests on [Sauce Labs](https://saucelabs.com/)
