### ISSUE TITLE
Cache fingerprint

### ISSUE THREAD

**Issue by stryju** [ericelliott/cuid#26]
wouldn't it make sense to store fingerprint in a variable and only run it once when needed?

**Comment by ericelliott** [comment]
Sure, but we should [modularize the build](https://github.com/ericelliott/cuid/issues/25#issue-90140425) first.

**Comment by ericelliott** [comment]
The build is better now. Would you like to take a crack at caching the fingerprint?

**Comment by stryju** [comment]
this seems to be done already https://github.com/ericelliott/cuid/blob/master/source/client/index.js#L4

**Comment by ericelliott** [comment]
Cool! =)

**Comment by stryju** [comment]
caching-related issue(s) moved to the appropriate repo(s)
