### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/cuid#28]
The [Travis build is currently failing](https://travis-ci.org/ericelliott/cuid). Looks like a broken package dependency.

**Comment by therealklanni** [comment]
This is due to the fact that the npm version that comes with node 0.8 doesn't support the `^` operator in semver. See [cuid built with node 0.10](https://travis-ci.org/therealklanni/cuid). Maybe it's time to drop 0.8 support?

**Comment by ericelliott** [comment]
Yes. :+1:
