### ISSUE TITLE
Consider Standard JavaScript?

### ISSUE THREAD

**Issue by therealklanni** [ericelliott/cuid#31]
Would you consider moving away from jshint/eslint to use [Standard JavaScript](https://github.com/feross/standard) instead?

**Comment by ericelliott** [comment]
No. ESLint. =)

Standard JavaScript is missing a lot of ESLint features we need, and... they call it Standard JavaScript, but they promote a style that is not the least bit idiomatic.

I'm all for tossing idiomatic out the window if we can improve on the existing idiomatic style, but we should do that in repos that *won't be enforced across lots of orgs*, until that new style becomes the uncontroversial idiomatic style.

Calling something "standard" doesn't make it so.

**Comment by ericelliott** [comment]
I edited the above comment after I realized this wasn't one of the boilerplate repos. ;)

**Comment by therealklanni** [comment]
I agree with your points. I'm also not completely onboard with it, but lots of influential folks are starting to use it, so I thought I'd ask. :)
