### ISSUE TITLE
How are these sequential? (meta)

### ISSUE THREAD

**Issue by sjl2024** [ericelliott/cuid#46]
... If they're generated on different browsers or machines, and then inserted to the database later, won't they be in some random order? Am I totally missing the point? (I think so, sorry about that!) This looks really cool, but I'm struggling to understand the bit about them being sequential. If they were only sequential because they were being generated on ONE machine, then why wouldn't you just use an auto-increment int or bigint?

**Comment by ericelliott** [comment]
They're not guaranteed to be sequential. I should clarify that in the docs. Would you like to propose a PR?

**Comment by pieterjandesmedt** [comment]
Cuids generated by the same process within the same millisecond are [monotonically increasing](https://en.wikipedia.org/wiki/Monotonic_function) though. Between different processes on different machines not so much, but if their clocks are in sync, they're also more or less monotonically increasing.

Monotonically increasing keys are good for doing binary searches, so it's good for primary key index performance.

I agree the docs should be clearer on that. Cuids are not sequential at all in the sense that the next one is 'one more' than the previous one. I'll propose a PR.
