### ISSUE TITLE
RegExp for validation?

### ISSUE THREAD

**Issue by stockholmux** [ericelliott/cuid#50]
Is there a regular expression to validate CUIDs?

**Comment by hilkeheremans** [comment]
Check out https://github.com/smallhelm/is-cuid and https://www.npmjs.com/package/is-cuid

**Comment by stockholmux** [comment]
Nice! This should be in the readme for this project - I would have never found this without your help.

**Comment by rsp** [comment]
@stockholmux @hilkeheremans Note that `is-cuid` returns `true` for strings like this:

* c:\autoexec.bat
* comment=lorem+ipsum&json={"title":"Lorem","message":"Lorem%20ipsum%20dolor%20sit[...]"}

which I personally wouldn't consider a valid cuid.

See: https://runkit.com/rsp/59ba67877e8de600126d4b85

**Comment by hilkeheremans** [comment]
Yes, we noticed that as well recently. Thanks for mentioning!
