### ISSUE TITLE
Will cuid length always be 25?

### ISSUE THREAD

**Issue by asafyish** [ericelliott/cuid#51]
Hi,

Is cuid will always return a length 25 string ?
Need to know for setting VARCHAR length.
Couldn't find an exact answer about it.

Thanks !

**Comment by ericelliott** [comment]
Hi,

I'm not sure of the answer off the time of my head, but it shouldn't be possible for the length to vary more than 4 chars.

**Comment by louisabraham** [comment]
Hi, does it mean it will vary in [21, 25], [23, 27], [25, 29] or [21, 29] ?

**Comment by MurzNN** [comment]
Declared fixed length of cuid (eg 32 characters) will be greatly improve database performance, because storing and operating with cells, having fixed length (eg `Char(32)`), is much easier and quicker, than variable (`VarChar(32)`).

**Comment by ericelliott** [comment]
This standard is a decade old. We probably shouldn't go making changes that could break people's apps unless we have a really compelling reason to.
