### ISSUE TITLE
Make the starting symbol customizable

### ISSUE THREAD

**Issue by tindli** [ericelliott/cuid#57]
Would be great to have a way to customize the starting character. 
It could be given as a parameter to the cuid() function. The "c" could be the default if not given... 

If customizable, one could create specific classes of IDs that would allow some backend decisions based on the type of ID received...

**Comment by ericelliott** [comment]
In general, it's a bad idea to parse information out of identifiers -- you're really mixing concerns when you do so.

If you really must do something like that, you could easily wrap `cuid` and concatenate whatever you want to it.

**Comment by tindli** [comment]
ok thanks, trying to keep them pure.
