### ISSUE TITLE
Add option to reconstruct timestamp

### ISSUE THREAD

**Issue by pkese** [ericelliott/cuid#63]
I'm using `cuid` for logging stuff into a document database in objects like this:
```
{
  id: cuid(),
  timestamp: new Date.getTime(),
  type: 'content-specific',
  content: {...some_data}
}
```
If I could somehow safely reconstruct the `timestamp` back from `id`, I could omit having to store the timestamp in the database thus saving myself a lot of space.

Any option to add such feature?

**Comment by ericelliott** [comment]
Is it possible? Sure. Just break out the timestamp and reverse the encoding.

Is it wise? Probably not. What if in the future you want to switch id generators, or what if in the future we make a breaking change to the cuid structure?

My advice: Space is cheap. Take the hit.

**Comment by pkese** [comment]
Will do. Thanks.

**Comment by ericelliott** [comment]
=)
