### ISSUE TITLE
cuid as partition key

### ISSUE THREAD

**Issue by kjmiller1** [ericelliott/cuid#74]
Due to the c{timestamp}... structure, I have concerns about "todays" items creating a hot spot in a distributed data store for my use-case (long history of items, todays items are used heavily, using aws DynamoDB).

Thoughts on the validity of my concern?

**Comment by ericelliott** [comment]
Most distributed storage systems allow you to create your own partitioning hash function. I would give it a try, and if it does indeed create a hotspot, swap out the hash function to solve it.
