### ISSUE TITLE
Database index fragmentation

### ISSUE THREAD

**Issue by msageryd** [ericelliott/cuid#80]
Eric, you write that the sequential nature of cuid makes for better performance when used as primary keys in databases. I'm currently trying to choose what id concept to use and the more I read the more I understand that this is hard.

It seems that both the placement of the timestamp part of the uuid AND big/little endian concept of different database engines and OSes matters. Do you have any plans to make cuid more compatible with different RDBMs by making the timestamp style tweakable?

Maybe some interesting reading: https://github.com/richardtallent/RT.Comb

I'm sorry to say that I don't have the competence to be able to PR something. I stumbled over cuid while researching. I have always held you high for competence and innovation in the Javascript community, and was hoping that "this is it, this could solve my id needs" :)

**Comment by ericelliott** [comment]
I  have  no  current  plans,  but  I'm  open  to  it.
