### ISSUE TITLE
Status of cuid

### ISSUE THREAD

**Issue by julien-f** [ericelliott/cuid#82]
Hi everyone,

I'm wondering what is the dev status of this library, is it still actively maintained?
Is it safe to bet on it for a new Node project?

Thanks for your answer :)

**Comment by ericelliott** [comment]
Hi,

1. cuid works great in Node. I use it daily, and it should be fine to use in new Node projects. The current outstanding issues mostly impact developers using client-side code in browsers -- in particular, web workers and service workers.

2. We have a few outstanding issues that are waiting to be cleared, and a couple of pull requests attempting to do just that. I don't have time to actively push those PRs through the pipeline, so I rely on community support for help. So far, a couple of devs have attempted to modernize cuid, but neither have managed to get the build pipeline green and ensure that cuid will continue to work smoothly for all of the developers who rely on it. If you'd like to help with that, please check out [this issue](https://github.com/ericelliott/cuid/pull/72) and take a crack at it.

Thanks!

**Comment by julien-f** [comment]
Thank you for this prompt and complete answer :)

Have a nice day.
