### ISSUE TITLE
Landing date for 2.0.0

### ISSUE THREAD

**Issue by PatrickKing** [ericelliott/cuid#87]
For reasons related to a problem in a CUID 1.3.8 [dependency](https://github.com/zloirock/core-js/issues/129), I'm very excited for the jump to 2.0.0

Any word on when it lands in NPM? Any API changes to know about?

Thanks!

**Comment by ericelliott** [comment]
See the checklist in #84 

I don't have time to push this through, so I'm counting on the community. If you want it, please make it happen! =)
