### ISSUE TITLE
https://usecuid.org/ uses incorrect certificate

### ISSUE THREAD

**Issue by iamale** [ericelliott/cuid#89]
https://usecuid.org/ uses Github's SSL certificate, which is only valid for *.github.io, not custom domains. Unfortunately, Github doesn't allow custom certificates, but you can switch to [Netlify](https://netlify.com) (which is free and should work as a drop-in replacement here).

**Comment by ericelliott** [comment]
Thanks. Looks like somebody hijacked the domain somehow. I redeployed GitHub user pages and rewrote the NS records, and it looks like I've regained control - but I have no idea how the hack happened in the first place. 😟
