### ISSUE TITLE
Question: Is there a Changelog?

### ISSUE THREAD

**Issue by mbifulco** [ericelliott/cuid#91]
Hi there - congrats on recently releasing 2.0.0 and 2.0.1! I'm looking to upgrade from 1.3.8, and I want to make sure I understand any breaking changes before I do so.  I realize it adds a bit of work, but can you add a CHANGELOG.md, or release notes on the GitHub releases page that documents what's new? It'll be helpful in the future.

I should add that I'd be happy to help with said documentation, if possible... but I don't necessarily know what's new, or the motivation behind the changes.

**Comment by ericelliott** [comment]
The new version uses a browserify bundle and lets the build system determine which versions of fingerprint to use based on the build target.

```js
  "browser": {
    "./lib/fingerprint.js": "./lib/fingerprint.browser.js"
  },
  "react-native": {
    "./lib/fingerprint.js": "./lib/fingerprint.react-native.js"
  },
```

The API has not changed at all, but the new build mechanism may cause build systems to behave differently.

**Comment by mbifulco** [comment]
Definitely will.  2.0.1 was giving me some hiccups this morning when I opened this issue, but 2.0.2 seems 👌 Thanks @ericelliott!

It'd still be useful for others to see your comment above in [the release notes](https://github.com/ericelliott/cuid/releases), if you don't mind!

**Comment by ericelliott** [comment]
Done.

**Comment by Ahimta** [comment]
Would be very helpful to have a `CHANGELOG.md`, especially for people who are not familiar with GitHub releases page :).

**Comment by ericelliott** [comment]
I do not want to maintain a changelog. If you know an automated solution that will build it from the release notes, I'm interested.

**Comment by Ahimta** [comment]
Seems like most tools do the exact opposite (CHANGELOG.md -> GH release).
One example: [github-release-from-changelog](https://github.com/MoOx/github-release-from-changelog)
