### ISSUE TITLE
Cannot find module './lib/fingerprint.js' from 'index.js'

### ISSUE THREAD

**Issue by philippefutureboy** [ericelliott/cuid#92]
**cuid:** v2.0.1
**Node.JS:** v8.9.1
**npm:** v5.5.1
**yarn:** v1.3.2
**Import style:** require
**Environment:** TypeScript
**OS:** MacOS High Sierra 10.13.1

When using `require` to load `cuid`, the error `Cannot find module './lib/fingerprint.js' from 'index.js'` is thrown at resolve time, rendering v2.0.1 unusable.

Looking in the node_module folder, it seems like the lib files are not included in the npm module. It doesn't seem to be an .npmignore problem since you don't have an .npmignore file.

Cheers!

**Comment by Flet** [comment]
It looks like there is a leftover `files` key in `package.json` that forces npm to only publish the `dist` directory. I think this is left over from a previous iteration of this package and is not valid anymore.

Removing the `files` attribute from `package.json` and republishing should fix it! 

@ericelliott sorry I didn't catch this earlier when I asked for v2.0.0 to be published :( Please let me know if I can help.
