### ISSUE TITLE
Database column type

### ISSUE THREAD

**Issue by satb** [ericelliott/cuid#95]
If the database column type is a string, could the monotonously increasing nature of the id be taken advantage of with a varchar column type in the db? Say in postgresql or mysql? Are there any downsides/tradeoffs of using varchar id instead of a long?

**Comment by ericelliott** [comment]
[Yes, Postgres indexes are searched using binary search](http://patshaughnessy.net/2014/11/11/discovering-the-computer-science-behind-postgres-indexes).

There are no practical downsides that you should worry about that I can think of, whereas, there are many downsides to using an auto-incrementing long. See the "Horizontal scalability" section in the docs.

**Comment by satb** [comment]
@ericelliott - Thank you. But how is the monotonically increasing nature being taken advantage of with an index (btree)? Wouldn't any column values (even non monotonically increasing) work the same way?

**Comment by ericelliott** [comment]
Good question. There is no single answer to it though because not all db and shard hash keys take advantage of monotonic order.

When they do, they can take advantage of append-only key sorts and and [consistent hash qualities](https://en.m.wikipedia.org/wiki/Hash_table#Monotonic_keys).

**Comment by mkgo** [comment]
What would be the recommendation, in the case of MySQL for the database field type?
